In [ ]:
from skimage.transform import resize
import numpy as np
from skimage.util import random_noise
from PIL import Image

"""
Logic is from https://stackoverflow.com/a/71822506
Adding random nose in an even distribution across the image
Doing it in 3 layers helps creating varying size of grain, as we downscale and then upscale 
"""
def gen_noise_mask(rows, cols, seperatedColorChannels: bool):
    val = 0.01 # random.uniform(0.036, 0.107)
    # Full resolution
    noise_im1 = np.zeros((rows, cols, 3))
    noise_im2 = np.zeros((rows // 2, cols // 2, 3))
    noise_im3 = np.zeros((rows // 4, cols // 4, 3))
    
    noise_im1 = random_noise(noise_im1, mode='gaussian', var=val ** 2, clip=False)
    

    # Half resolution
    noise_im2 = random_noise(noise_im2, mode='gaussian', var=(val * 2) ** 2, clip=False)  # Use val*2 (needs tuning...)
    noise_im2 = resize(noise_im2, (rows, cols))  # Upscale to original image size

    # Quarter resolution
    noise_im3 = random_noise(noise_im3, mode='gaussian', var=(val * 4) ** 2, clip=False)  # Use val*4 (needs tuning...)
    noise_im3 = resize(noise_im3, (rows, cols))  # What is the interpolation method?

    noise_im = noise_im1 + noise_im2  + noise_im3  # Sum the noise in multiple resolutions (the mean of noise_im is around zero).
    return noise_im

def noiseGenerator(im, seperateColorChannels:bool):
    im_arr = np.asarray(im)

    rows, cols, color_channels = im_arr.shape

    noise_mask = np.zeros((rows, cols, color_channels ), 'float64')
    noise_mask = gen_noise_mask(rows, cols, seperateColorChannels)

    noisy_img = im_arr / 255 + noise_mask  # Add noise_im to the input image.
    noisy_img = np.round((255 * noisy_img)).clip(0, 255).astype(np.uint8)
    return Image.fromarray(noisy_img)

In [ ]:
import os
path = ''
new_path=''


directory = os.fsencode(path)
for file in os.listdir(directory):
     filename = os.fsdecode(file)
     path_to_file = f'{path}{filename}'
     path_to_new_file = f'{new_path}{filename}'
     filename_lower = filename.lower()
     if filename_lower.endswith(".jpeg") or filename_lower.endswith(".png") or filename_lower.endswith(".jpg"): 
          grainy = noiseGenerator(Image.open(fp=path_to_file))
          grainy.save(fp=path_to_new_file)
          



[[[-0.06216595  0.00323056 -0.04342969]
  [-0.0148957   0.01743072 -0.04068328]
  [-0.00803748  0.01836358 -0.00900717]
  ...
  [-0.0487308  -0.03574194  0.0433664 ]
  [ 0.00634814  0.0207078   0.00029457]
  [-0.00622354  0.03845419  0.00997482]]

 [[-0.0746666   0.03067033 -0.02778874]
  [-0.05324334  0.00052928  0.00651396]
  [ 0.03001576  0.05987223  0.00492686]
  ...
  [-0.02347064  0.02161186 -0.00401427]
  [ 0.03970867  0.03484996  0.07290084]
  [ 0.03923914  0.01728838 -0.00951996]]

 [[ 0.00721596  0.05007211 -0.01581578]
  [ 0.02229513 -0.00157787  0.04822182]
  [-0.02159272  0.03301039 -0.01478798]
  ...
  [ 0.00381286 -0.00279713  0.02357804]
  [ 0.03243032 -0.00450128 -0.03331625]
  [-0.04651167 -0.04147455  0.03138766]]

 ...

 [[ 0.02291938  0.01169206  0.00033583]
  [-0.06264681  0.03429306  0.01611264]
  [ 0.10704083  0.00247724 -0.01209383]
  ...
  [ 0.02660817 -0.0308108  -0.00503543]
  [ 0.0050955   0.01008925 -0.01613673]
  [ 0.0089545   0.01633281  0.0286597 ]]

 [